"""Add task and last_heartbeat

Revision ID: 05c1e7cc4286
Revises: 849f5e4c2a7e
Create Date: 2026-07-02 02:06:38.073043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c1e7cc4286'
down_revision: Union[str, Sequence[str], None] = '849f5e4c2a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('task', sa.String(), nullable=True))
    op.add_column('robots', sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'last_heartbeat')
    op.drop_column('robots', 'task')
    # ### end Alembic commands ###
